/*
In this AdminLogin class Admin and Employee can login
we have adminLogin() method for admin login and employeeLogin() method 
for employee login.
*/
package coffeshop;

import java.io.File;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class AdminLogin extends javax.swing.JFrame {

    public static String role = "";
    
    private ObjectOutputStream outputStream;
    private ObjectInputStream inputStream;
    private ArrayList<Employee> employeeList;
    private File employeeFile;

    public AdminLogin() {
        initComponents();

        outputStream = null;
        inputStream = null;
        employeeList = new ArrayList<>();
        employeeFile = new File("employee.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        role_admin = new javax.swing.JRadioButton();
        role_employee = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Coffe Shop Management");

        jLabel2.setText("User Name");

        jLabel3.setText("Password");

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        role_admin.setText("Admin");
        role_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                role_adminMouseClicked(evt);
            }
        });

        role_employee.setText("Employee");
        role_employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                role_employeeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(role_admin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(role_employee))
                    .addComponent(loginBtn)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user_name)
                        .addComponent(jLabel3)
                        .addComponent(password)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(role_admin)
                    .addComponent(role_employee))
                .addGap(9, 9, 9)
                .addComponent(loginBtn)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadFile() {
        if (employeeFile.isFile()) {
            try {
                inputStream = new ObjectInputStream(new FileInputStream(employeeFile));
                employeeList = (ArrayList<Employee>) inputStream.readObject();
                inputStream.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("File does't exists!");
        }
    }

    private void adminLogin(String userName, String pass) {

        if (userName.equals("admin") && pass.equals("admin")) {

            Manager manager = new Manager();
            manager.setLocationRelativeTo(null);
            manager.setVisible(true);
            dispose();

        } else {
            JOptionPane.showMessageDialog(this, "user name or password is wrong! Please try again");
        }
    }

    private void employeeLogin(String email, String pass) {

        loadFile();
        boolean isFind = false;

        for (int i = 0; i < employeeList.size(); i++) {
            if (employeeList.get(i).getEmail().equals(email)
                    && employeeList.get(i).getPassword().equals(pass)) {
                isFind = true;
                break;
            }
        }

        if (isFind) {
            EmployeeWindow employeeWindow = new EmployeeWindow();
            employeeWindow.setLocationRelativeTo(null);
            employeeWindow.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "user name or password is wrong! Please try again");
        }

    }

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        String userName = "";
        userName = user_name.getText();
        String pass = "";
        pass = password.getText();

        if (!userName.isEmpty()) {
            if (!pass.isEmpty()) {

                if (role_admin.isSelected()) {
                    role = "admin";
                    adminLogin(userName, pass);
                } else if (role_employee.isSelected()) {
                    role = "employee";
                    employeeLogin(userName, pass);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Please enter password");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter user name");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void role_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_role_adminMouseClicked

        if (role_admin.isSelected()) {
            role_employee.setSelected(false);
        }

    }//GEN-LAST:event_role_adminMouseClicked

    private void role_employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_role_employeeMouseClicked

        if (role_employee.isSelected()) {
            role_admin.setSelected(false);
        }


    }//GEN-LAST:event_role_employeeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField password;
    private javax.swing.JRadioButton role_admin;
    private javax.swing.JRadioButton role_employee;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
