/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffeshop;

import java.awt.PopupMenu;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class OrderForm extends javax.swing.JFrame {

    /**
     * Creates new form OderForm
     */
    private ObjectOutputStream outputStream;
    private ObjectInputStream inputStream;
    private ArrayList<Coffee> coffeeList;
    private ArrayList<Orders> ordersList;
    private File coffeeFile;
    private File ordersFile;

    public OrderForm() {
        initComponents();

        outputStream = null;
        inputStream = null;
        coffeeList = new ArrayList<>();
        ordersList = new ArrayList<>();
        coffeeFile = new File("coffee.txt");
        ordersFile = new File("orders.txt");

        loadFile();
        fillCoffeeList();
        quantity.setValue(Integer.valueOf(1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customer_name = new javax.swing.JTextField();
        go_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        coffee_name = new javax.swing.JComboBox<>();
        quantity = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billing_table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        total_price = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        check_out = new javax.swing.JButton();
        add_cart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Order Form");

        jLabel2.setText("Customer Name");

        go_back.setText("Go Back");
        go_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_backActionPerformed(evt);
            }
        });

        jLabel3.setText("Coffee Name");

        jLabel4.setText("Quantity");

        billing_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Coffee Name", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(billing_table);

        jLabel5.setText("Billing Table");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Total Price");

        total_price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_price.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("RS");

        check_out.setText("Check Out");
        check_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_outActionPerformed(evt);
            }
        });

        add_cart.setText("Add to Cart");
        add_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(go_back)
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(coffee_name, javax.swing.GroupLayout.Alignment.LEADING, 0, 180, Short.MAX_VALUE)
                                .addComponent(customer_name, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(add_cart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(total_price)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addComponent(check_out))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(go_back))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coffee_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(total_price)
                    .addComponent(jLabel7)
                    .addComponent(add_cart))
                .addGap(32, 32, 32)
                .addComponent(check_out)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadFile() {
        if (coffeeFile.isFile()) {
            try {
                inputStream = new ObjectInputStream(new FileInputStream(coffeeFile));
                coffeeList = (ArrayList<Coffee>) inputStream.readObject();
                inputStream.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("File does't exists!");
        }
    }

    public void loadOrdersFile() {
        if (ordersFile.isFile()) {
            try {
                inputStream = new ObjectInputStream(new FileInputStream(ordersFile));
                ordersList = (ArrayList<Orders>) inputStream.readObject();
                inputStream.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("File does't exists!");
        }
    }

    private void fillCoffeeList() {

        for (int i = 0; i < coffeeList.size(); i++) {
            String coffee = coffeeList.get(i).getCoffeeName();
            coffee_name.addItem(coffee);
        }
    }

    private void go_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_backActionPerformed

        EmployeeWindow employeeWindow = new EmployeeWindow();
        employeeWindow.setLocationRelativeTo(null);
        employeeWindow.setVisible(true);
        dispose();

    }//GEN-LAST:event_go_backActionPerformed

    private void add_cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cartActionPerformed

        String customerName;
        int coffeIndex;
        int qty;

        customerName = customer_name.getText();
        coffeIndex = coffee_name.getSelectedIndex();
        qty = (int) quantity.getValue();

        String coffeName = coffeeList.get(coffeIndex).getCoffeeName();
        double coffePrice = coffeeList.get(coffeIndex).getCoffeePrice();

        double totalPrice = coffePrice * qty;

        DefaultTableModel model = (DefaultTableModel) billing_table.getModel();

        Object[] obj = new Object[4];
        obj[0] = customerName;
        obj[1] = coffeName;
        obj[2] = qty;
        obj[3] = totalPrice;
        model.addRow(obj);
        double totalGrand = Double.parseDouble(total_price.getText()) + totalPrice;
        total_price.setText(String.valueOf(totalGrand));

    }//GEN-LAST:event_add_cartActionPerformed

    private void check_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_outActionPerformed

        DefaultTableModel model = (DefaultTableModel) billing_table.getModel();
        loadOrdersFile();

        String cusName = "";
        String coffeeName = "";
        int qty = 0;
        double price = 0.0;

        for (int i = 0; i < model.getRowCount(); i++) {
            cusName = (String) model.getValueAt(i, 0);
            coffeeName = (String) model.getValueAt(i, 1);
            qty = (int) model.getValueAt(i, 2);
            price = (double) model.getValueAt(i, 3);
            ordersList.add(new Orders(cusName, coffeeName, qty, price));
        }

        try {
            
            outputStream = new ObjectOutputStream(new FileOutputStream(ordersFile));
            outputStream.writeObject(ordersList);
            outputStream.close();
            JOptionPane.showMessageDialog(null, "Successfully Orderd");

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_check_outActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_cart;
    private javax.swing.JTable billing_table;
    private javax.swing.JButton check_out;
    private javax.swing.JComboBox<String> coffee_name;
    private javax.swing.JTextField customer_name;
    private javax.swing.JButton go_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner quantity;
    private javax.swing.JLabel total_price;
    // End of variables declaration//GEN-END:variables
}
